language: php
phps:
  - 5.3
  - 5.4
branches:
  only:
    - master
    - develop

before_script:
  - wget -nc http://getcomposer.org/composer.phar
  - php composer.phar --dev install

script:
  - vendor/bin/behat
  - phpunit
  
